#******************************************************************#
# Sample Makefile.config.  Be sure to edit this to your likings    #
# and copy it to Makefile.config.                                  #
#******************************************************************#

#------------------------------------------------------------------#
# Select the target system                                         #
# (define your own, if needed!)                                    #
#------------------------------------------------------------------#
#SYSTEM =	"Standard SQL"
SYSTEM =	"Standard OpenMP"
#SYSTEM =	"Standard MPI"
#SYSTEM =	"Standard MPI+OpenMP"
#SYSTEM =	"SuperMUC"
#SYSTEM =	"Debug"

#------------------------------------------------------------------#
# DEFINEFLAGS                                                      #
#------------------------------------------------------------------#

# nIFTy cosmology
#=================
#CART:
#DEFINEFLAGS	=	-DMULTIMASS -DGAS_PARTICLES  -DVERBOSE2  #-DAHFignore_ugas #-DMETALHACK -DAHFexciseSubhaloStars
#MUSIC_GASTROPHYSICS:
#DEFINEFLAGS     =       -DMULTIMASS -DGAS_PARTICLES -DMETALHACK -DAHFexciseSubhaloStars
#SPHS:
#DEFINEFLAGS	=	-DMULTIMASS -DGAS_PARTICLES


# B01, B20, B50, B100
#------------------------------------------------------------------
#DEFINEFLAGS	=	-DMULTIMASS

# B320
#------------------------------------------------------------------
#DEFINEFLAGS	=	-DAHFshellshape

# Box20b
#------------------------------------------------------------------
#DEFINEFLAGS	=	-DMULTIMASS -DBYTESWAP

# HaloesGoingMAD
#------------------------------------------------------------------
#DEFINEFLAGS	=	-DMULTIMASS -DGAS_PARTICLES

# SubhaloesGoingNotts (A1-A3, A4-5)
#------------------------------------------------------------------
#DEFINEFLAGS	=	-DMULTIMASS -DAHFrfocus -DDOUBLE
#DEFINEFLAGS	=	-DMULTIMASS #-DAHFnewCloseRefDist

# Box160, MW1.512
#------------------------------------------------------------------
#DEFINEFLAGS	=	-DMULTIMASS -DGAS_PARTICLES

# LGR2Mpc, ... (basically any GADGET output produced by Gustavo!)
#------------------------------------------------------------------
#DEFINEFLAGS    =      -DMULTIMASS -DGAS_PARTICLES -DMETALHACK #-DAHFdisks #-DAHFnewHaloIDs #-DAHFexciseSubhaloStars #-DAHFbinary

# CLUES-gasblobs
#------------------------------------------------------------------
#DEFINEFLAGS	=	-DMULTIMASS -DGAS_PARTICLES -DAHFptfocus=0 -DAHFnoremunbound -DDVIR_200RHOCRIT -DMANUAL_DVIR=200

# MW1.1024g1bwk, g1536, g15784, GALFOBS
#------------------------------------------------------------------
#DEFINEFLAGS    =      -DMULTIMASS -DGAS_PARTICLES -DBYTESWAP

# LTBvoids
#------------------------------------------------------------------
#DEFINEFLAGS    =      -DAHFrfocus -DDVIR_200RHOCRIT

# GHALO
#------------------------------------------------------------------
#DEFINEFLAGS	=	-DMULTIMASS -DTIPSY_ZOOMDATA -DGAS_PARTICLES
#DEFINEFLAGS	=	-DMULTIMASS -DGAS_PARTICLES -DBYTESWAP

# d2100
#-------
#DEFINEFLAGS	=	-DMULTIMASS -DGAS_PARTICLES -DBYTESWAP

# simuCroCo tests
#-----------------
#DEFINEFLAGS	=	-DGADGET 

# sigmaH flags for Jubilee H0voids project
#------------------------------------------
#DEFINEFLAGS	=	-DMULTIMASS

# DPhalos
#---------
#DEFINEFLAGS	=	-DDPhalos
#DEFINEFLAGS	=	-DGADGET

# Sussing Merger Trees
#======================
#DEFINEFLAGS	=	-DSUSSING2013

# AHF2
#======
# general 
#DEFINEFLAGS	+=	-DVERBOSE -DVERBOSE2 -DPATCH_DEBUG -DDEBUG_AHF2 -DAHFgridtreefile -DAHFwritePreliminaryHalos 
#//Defined by default in define.h. If not defined, cubekeys are 64bits long, and deepest refinement level is 21.
#DEFINEFLAGS	+=	-DCUBEKEY_128
#//Review number of subcubes and stored particles per level, printing it to log and to generate_tree.log if activated with -DGENERATE_TREE_LOG
#DEFINEFLAGS	+=	-DREVIEW_SUBCUBES_FORMATION
# SubhalosGoingNotts
#DEFINEFLAGS	+=	-DMULTIMASS
# HalosGoingMAD
#DEFINEFLAGS	+=	-DGAS_PARTICLES



#------------------------------------------------------------------#
# Set environment for the system                                   #
#------------------------------------------------------------------#
ifeq ($(SYSTEM), "Standard SQL")
	CC         	=	gcc -std=c99 -fopenmp
	FC 	      	=	gfortran
	OPTIMIZE	=	-O2
	CCFLAGS		=
	LNFLAGS		=	-lsqlite3
	DEFINEFLAGS	+=	-DWITH_OPENMP -DAHF_SQL
	MAKE		=	make
endif

ifeq ($(SYSTEM), "Standard OpenMP")
	CC         	=	gcc -std=c99 -fopenmp 
	FC 	      	=	gfortran
	OPTIMIZE	=	-O2
	CCFLAGS		=	
	LNFLAGS		=
	DEFINEFLAGS	+=	-DWITH_OPENMP 
	MAKE		=	make
endif

ifeq ($(SYSTEM), "Standard Serial")
	CC              =       gcc -std=c99 -g -fopenmp
	FC              =       gfortran
	OPTIMIZE        =       -O2
	CCFLAGS         =
	LNFLAGS         =
# -DSERIAL is not used yet, only for seeing when we are compiling a Serial version on the compiling messages
	DEFINEFLAGS	+=	-DSERIAL 
	DEFINEFLAGS	+=	-DGENERATE_TREE_LOG
	DEFINEFLAGS	+=	-DPATCH_THREADS_LOG
	DEFINEFLAGS	+=	-DREVIEW_SUBCUBES_FORMATION
	MAKE            =       make
endif

ifeq ($(SYSTEM), "Standard MPI")
	CC         	=	mpicc -std=c99 -Wall -W -fopenmp
	FC         	=	mpif90
	OPTIMIZE	=	-O2
	CCFLAGS		=
	LNFLAGS		=
	DEFINEFLAGS	+=	-DWITH_MPI
	MAKE		=	make
endif

ifeq ($(SYSTEM), "Standard MPI+OpenMP")
	CC         	=	mpicc -std=c99 -Wall -W -fopenmp
	FC         	=	g77
	OPTIMIZE	=	-O2
	CCFLAGS		=
	LNFLAGS		=
	DEFINEFLAGS	+=	-DWITH_MPI -DWITH_OPENMP
	DEFINEFLAGS	+=	-DGENERATE_TREE_LOG
	DEFINEFLAGS	+=	-DPATCH_THREADS_LOG
	DEFINEFLAGS	+=	-DREVIEW_SUBCUBES_FORMATION
		MAKE		=	make
endif

ifeq ($(SYSTEM), "SuperMUC")
  CC        =       mpicc -compiler gcc -m64 -mcmodel=large -std=c99 -Wall -W -fopenmp
	FC       	=	g77
	OPTIMIZE	=	-O2 
	CCFLAGS		=
	LNFLAGS		=
	DEFINEFLAGS	+=	-DWITH_MPI -DWITH_OPENMP
	MAKE		=	make
endif

ifeq ($(SYSTEM), "Debug")
	CC         	=	gcc -std=c99 -g -fopenmp
	FC 	      	=	g95
	OPTIMIZE	=	-O2 
	CCFLAGS		=	-g 
#Compile and link with -pg flag for Gprof
	CCFLAGS		+=	-pg
	LNFLAGS		=	-pg
	DEFINEFLAGS     +=      -DGENERATE_TREE_LOG
	DEFINEFLAGS	+=	-DGENERATE_TREE_LOG
	DEFINEFLAGS	+=	-DPATCH_THREADS_LOG
	DEFINEFLAGS	+=	-DREVIEW_SUBCUBES_FORMATION
	
	DEFINEFLAGS	+=	
	MAKE		=	make
endif
