#******************************************************************#
# Sample Makefile.config.  Be sure to edit this to your likings    #
# and copy it to Makefile.config.                                  #
#******************************************************************#

#------------------------------------------------------------------#
# Select the target system                                         #
# (define your own, if needed!)                                    #
#------------------------------------------------------------------#
#SYSTEM =	"Standard SQL"
SYSTEM =	"Standard OpenMP"
#SYSTEM =	"Standard MPI"
#SYSTEM =	"Standard MPI+OpenMP"
#SYSTEM =	"SuperMUC"
#SYSTEM =	"Debug"

#------------------------------------------------------------------#
# DEFINEFLAGS                                                      #
#------------------------------------------------------------------#
#
# NOTE: ALWAYS CHECK WHICH FLAGS HAVE BEEN SET IN define.h
#
#-------------------------------------------------------------------
DEFINEFLAGS	= 

# nIFTy cosmology
#=================
#CART:
#DEFINEFLAGS	=	-DMULTIMASS -DGAS_PARTICLES  -DVERBOSE2  #-DAHFignore_ugas #-DMETALHACK -DAHFexciseSubhaloStars
#MUSIC_GASTROPHYSICS:
#DEFINEFLAGS     =       -DMULTIMASS -DGAS_PARTICLES -DMETALHACK -DAHFexciseSubhaloStars
#SPHS:
#DEFINEFLAGS	=	-DMULTIMASS -DGAS_PARTICLES


# B01, B20, B50, B100
#------------------------------------------------------------------
#DEFINEFLAGS	=	-DMULTIMASS

# B320
#------------------------------------------------------------------
#DEFINEFLAGS	=	-DAHFshellshape

# Box20b
#------------------------------------------------------------------
#DEFINEFLAGS	=	-DMULTIMASS -DBYTESWAP

# HaloesGoingMAD
#------------------------------------------------------------------
#DEFINEFLAGS	=	-DMULTIMASS -DGAS_PARTICLES

# SubhaloesGoingNotts (A1-A3, A4-5)
#------------------------------------------------------------------
#DEFINEFLAGS	=	-DMULTIMASS -DAHFrfocus -DDOUBLE
#DEFINEFLAGS	=	-DMULTIMASS #-DAHFnewCloseRefDist

# Box160, MW1.512
#------------------------------------------------------------------
#DEFINEFLAGS	=	-DMULTIMASS -DGAS_PARTICLES -DSUSSING2013

# LGR2Mpc, ... (basically any GADGET output produced by Gustavo!)
#------------------------------------------------------------------
#DEFINEFLAGS    =      -DMULTIMASS -DGAS_PARTICLES -DMETALHACK -DAHFexciseSubhaloStars #-DAHFdisks #-DAHFnewHaloIDs #-DAHFexciseSubhaloStars #-DAHFbinary

# CLUES-gasblobs
#------------------------------------------------------------------
#DEFINEFLAGS	=	-DMULTIMASS -DGAS_PARTICLES -DAHFptfocus=0 -DAHFnoremunbound -DDVIR_200RHOCRIT -DMANUAL_DVIR=200

# CLUES-Gasoline
#------------------------------------------------------------------
#DEFINEFLAGS	=	-DMULTIMASS -DGAS_PARTICLES -DAHFignore_ugas

# MW1.1024g1bwk, g1536, g15784, GALFOBS
#------------------------------------------------------------------
#DEFINEFLAGS    =      -DMULTIMASS -DGAS_PARTICLES -DBYTESWAP

# LTBvoids
#------------------------------------------------------------------
#DEFINEFLAGS    =      -DAHFrfocus -DDVIR_200RHOCRIT

# GHALO
#------------------------------------------------------------------
#DEFINEFLAGS	=	-DMULTIMASS -DTIPSY_ZOOMDATA -DGAS_PARTICLES
#DEFINEFLAGS	=	-DMULTIMASS -DGAS_PARTICLES -DBYTESWAP

# d2100
#-------
#DEFINEFLAGS	=	-DMULTIMASS -DGAS_PARTICLES -DBYTESWAP

# simuCroCo tests
#-----------------
#DEFINEFLAGS	=	-DGADGET 

# sigmaH flags for Jubilee H0voids project
#------------------------------------------
#DEFINEFLAGS	=	-DMULTIMASS

# DPhalos
#---------
#DEFINEFLAGS	=	-DDPhalos
#DEFINEFLAGS	=	-DGADGET

# Sussing Merger Trees
#----------------------
#DEFINEFLAGS	=	-DSUSSING2013

# simu2tipsy for GASOLINE-CLUES
#---------------------------------
#DEFINEFLAGS	=	-DGADGET -DMULTIMASS -DGAS_PARTICLES -DGINNUNGAGAP -DLGADGET

# GIZMO 
#-------
#DEFINEFLAGS     =       -DMULTIMASS -DGAS_PARTICLES -DWITH_HDF5 -DSUSSING2013 -DAHFexciseSubhaloStars -DMETALHACK

# GadgetX
#DEFINEFLAGS     =       -DMULTIMASS -DGAS_PARTICLES -DSUSSING2013 -DAHFexciseSubhaloStars -DMETALHACK -DIGNORE_BLACKHOLEAGES #-DAHFdisks #-DAHFdmonlypeaks


#------------------------------------------------------------------#
# Set environment for the system                                   #
#------------------------------------------------------------------#
LIB_HDF5	=	-L/Users/aknebe/bin/hdf5/lib -lhdf5
INC_HDF5	=	-I/Users/aknebe/bin/hdf5/include -DH5_USE_16_API

ifeq ($(SYSTEM), "Standard SQL")
	CC         	=	gcc -std=c99 -fopenmp
	FC 	      	=	gfortran
	OPTIMIZE	=	-O2
	CCFLAGS		=	
	LNFLAGS		=	-lsqlite3 
	DEFINEFLAGS	+=	-DWITH_OPENMP -DAHF_SQL
	MAKE		=	make
endif

ifeq ($(SYSTEM), "Standard OpenMP")
	CC         	=	gcc -std=c99 -fopenmp 
	FC 	      	=	gfortran
	OPTIMIZE	=	-O2
	CCFLAGS		=	
	LNFLAGS		=	 
	DEFINEFLAGS	+=	-DWITH_OPENMP 
	MAKE		=	make
endif

ifeq ($(SYSTEM), "Standard Serial")
	CC              =       gcc -std=c99 -g -fopenmp
	FC              =       gfortran
	OPTIMIZE        =       -O2
	CCFLAGS         =       
	LNFLAGS         =	
	MAKE            =       make
endif

ifeq ($(SYSTEM), "Standard MPI")
	CC         	=	mpicc -std=c99 -Wall -W -fopenmp
	FC         	=	mpif90
	OPTIMIZE	=	-O2
	CCFLAGS         =       ${INC_HDF5}
	LNFLAGS         =       ${LIB_HDF5}
	DEFINEFLAGS	+=	-DWITH_MPI
	MAKE		=	make
endif

ifeq ($(SYSTEM), "Standard MPI+OpenMP")
	CC         	=	mpicc -std=c99 -Wall -W -fopenmp
	FC         	=	g77
	OPTIMIZE	=	-O2
	CCFLAGS         =       ${INC_HDF5}
	LNFLAGS         =       ${LIB_HDF5} 

	DEFINEFLAGS	+=	-DWITH_MPI -DWITH_OPENMP
	MAKE		=	make
endif

ifeq ($(SYSTEM), "SuperMUC")
	CC	        =       mpicc -compiler gcc -m64 -mcmodel=large -std=c99 -Wall -W -fopenmp
	FC       	=	g77
	OPTIMIZE	=	-O2 
	CCFLAGS         =       ${INC_HDF5}
	LNFLAGS         =       ${LIB_HDF5}
	DEFINEFLAGS	+=	-DWITH_MPI -DWITH_OPENMP
	MAKE		=	make
endif

ifeq ($(SYSTEM), "Debug")
	CC         	=	gcc -std=c99 -g -fopenmp
	FC 	      	=	g95
	OPTIMIZE	=	-O2 
	CCFLAGS		=	-g 
#Compile and link with -pg flag for Gprof
	CCFLAGS		+=	-pg
	LNFLAGS		=	-pg
	DEFINEFLAGS	+=	
	MAKE		=	make
endif
